name: Generate preview of `semantic-release` changelog
on: [pull_request]
jobs:
  run-semantic-release-github-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npx semantic-release-github-pr --debug
